### ISSUE TITLE
Does growatt read slave ID 1 for SDM?

### ISSUE THREAD

**Issue by kmsj13** [3s1d/mbSdmGrowattMiddleware#1]
from your code:

fakesdm = growattbus.add_slave(1)
fakesdm.add_block('power', cst.ANALOG_INPUTS, 12, 18);

and 
fakesdm = growattbus.get_slave(1)
fakesdm.set_values('power', 12, sbuf)

Is it growatt reading slave ID 1 for fake SDM?

**Comment by 3s1d** [comment]
Yes. I have a real SDM630 connected to the second bus and before I feed the data to the inverter I manipulate them and provide them as ID 1. That way I can  limit the amount of power I am feeding to the grid to an arbitrary value instead of 'all or nothing'. (Nota Bene: This is required for my area as I am only allowed to export 70% of my solar peak power).
